### ISSUE TITLE
PARTICULAR - Mi Panel> Mis Peticiones (20/4) - (Media)

### ISSUE THREAD

**Issue by evaesqmor** [ISPP-LinkedPet/backend_isppet#137]
- [x] Aceptadas: El estado 'Pendiente de **Aceptación** de Pago' puede dar lugar a confusión
- [x] Después de pagar debería recargarse la página automáticamente

**Comment by jesushd103** [comment]
Nombre cambiado a: REALIZAR COBRO. Ya que el usuario en este estado debe de obtener el ingreso por el proceso de crianza, realizar cobro resulta intuitivo para el usuario.
