### ISSUE TITLE
Filtro en las ofertas de crianza

### ISSUE THREAD

**Issue by Alegomcab1** [ISPP-LinkedPet/backend_isppet#14]
En la vista de crianza, debe de haber un filtro con los siguientes campos:
- Precio
- Animal 
- Pedigree 
- Raza
- Genero

**Comment by rubbuemen** [comment]
He arreglado el filtro en backend con los nuevos valores indicados, que no coincidían con los que se detallaron la primera vez. Tiempo: 15 minutos
