### ISSUE TITLE
Sistema de reviews (28/03)

### ISSUE THREAD

**Issue by Alegomcab1** [ISPP-LinkedPet/backend_isppet#20]
- Una vez se esta llevando a cabo el servicio
   * Se genera codigo (Mis ofertas)
   * Codigo lo pone la otra persona (Mis ofertas aceptadas)
   * Una vez se ponga el codigo, se termina el servicio, se realiza el pago final
   * A partir de entonces se podra poner una review (Sistema de reviews por detallas)

**Comment by jesushd103** [comment]
Se tardó en hacer 4 horas.
