### ISSUE TITLE
Perfil de persona que hace la oferta (29/03)

### ISSUE THREAD

**Issue by Alegomcab1** [ISPP-LinkedPet/backend_isppet#25]
- Debe de aparecer mas información de la persona que hace la oferta
- Creacion de perfil con los datos con los que te registras
- NO mostrar tlf y correo
- **Extender informacion de las request, aniadiendo el perfil**
- Puntuacion de reviews

**Comment by evaesqmor** [comment]
En el Frontend, mostrar en el perfil los animales del usuario.
Botón para redirigir al formulario que crea al animal.

**Comment by evaesqmor** [comment]
Tipo Animal, Raza, Género, Fecha Nacimiento, Pedigree, Fotos del animal, Fotos de la documentación, Cartilla de vacunación
