### ISSUE TITLE
Cambiar el populate con datos reales (18/03)

### ISSUE THREAD

**Issue by DaviidGilB** [ISPP-LinkedPet/backend_isppet#3]

**Comment by DaviidGilB** [comment]
**DESARROLLO:**
Modificar el populate con datos correctos. Muy importante que las imágenes estén puestas de manera correcta, es decir, se deben guardar las imágenes en las carpetas correspondientes del proyecto y guardar en la bb.dd la ruta relativa a dicha foto: "/carpeta/foto", por ejemplo.

**Comment by jesushd103** [comment]
Listo, se ha tardado 5 horas para rellenar la db con muchos datos reales, se han corregido problemas de asociaciones de ids, se ha modificado posteriormente las tablas de la db con las necesidades de front, y se han colocado imagenes específicas para cada tipo de animal, con la ruta correcta como se especifíca arriba.
