### ISSUE TITLE
Aniadir entidad Mascota que aparezca en el perfil (30/03)

### ISSUE THREAD

**Issue by Alegomcab1** [ISPP-LinkedPet/backend_isppet#35]
- Entidad mascota:
    * Tipo de animal
    *** Fotos del  animal**
    * Raza
    * Pedigree
    * Edad
    *** Genero**
    *** Documentacion pasaporte **
    *** Documentacion cartilla**

- Aparecera en el perfil de esta manera (Falta documentacion, fotos del animal y genero)
![photo_2020-03-26_18-46-28.jpg](https://images.zenhubusercontent.com/5e72052bce80e723e04cd787/6ef8ed78-4d1c-45f1-bfdc-ccf44e9ca3aa)

**Comment by evaesqmor** [comment]
Formulario crear animal
