### ISSUE TITLE
Cambiar adopciones con tasas exclusivas para los refugios (18/03)

### ISSUE THREAD

**Issue by DaviidGilB** [ISPP-LinkedPet/backend_isppet#7]

**Comment by DaviidGilB** [comment]
**INCIDENCIA:**
- Realizar los cambios pertinentes para diferenciar la  creación y edición de adopciones en función del rol, ya que las adopciones de un refugio tienen tasas pero las de un particular no.

**Comment by RobertoHermoso** [comment]
20 minutos
